# This grabs hadoop-VERSION-snapshot.tar from the hadoop-dist/target directory and create a hadoop docker image
version: '3.3'
name: hadoop-four-nodes
services:
  namenode:
    image: hdfs-runtime:latest
    restart: always
    environment:
      HDFS_DATANODE_USER: root
    ports:
      - "9870:9870"
    volumes:
      - ./core-site.xml:/opt/hadoop-3.5.0-SNAPSHOT/etc/hadoop/core-site.xml
      - ./hdfs-site.xml:/opt/hadoop-3.5.0-SNAPSHOT/etc/hadoop/hdfs-site.xml
      - ./rack-topo.sh:/opt/rack-topo.sh
    entrypoint: bash namenode-entrypoint.sh
    networks:
      - intra

  datanode:
    image: hdfs-runtime:latest
    privileged: true
    restart: always
    volumes:
      - ./core-site.xml:/opt/hadoop-3.5.0-SNAPSHOT/etc/hadoop/core-site.xml
      - ./hdfs-site.xml:/opt/hadoop-3.5.0-SNAPSHOT/etc/hadoop/hdfs-site.xml
      - ./rack-topo.sh:/opt/rack-topo.sh
      - type: tmpfs
        target: /data/tmpfs1
        tmpfs:
          size: 104857600
      - type: tmpfs
        target: /data/tmpfs2
        tmpfs:
          size: 104857600
    entrypoint: bash datanode-entrypoint.sh
    networks:
      - intra
    deploy:
      replicas: 3

networks:
    intra: